version: "3.9"
services:
  sentinel-flow-ui:
    build: .
    ports:
      - "5001:5173"
    container_name: sentinel-flow-ui-container
    image: sentinel-flow-ui-image:latest
    environment:
      - SERVER_IP_PORT=172.16.10.102:20418
      - SERVER_FLOWABLE_IP_PORT=172.16.10.102:20419
