const Page404 = () => {
    return <div>page not found


        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
        <div>page not found</div>
    </div>
}

export default Page404